### ISSUE TITLE
Fix sound on click

### ISSUE THREAD

**Issue by csaethre19** [csaethre19/2450Hangman#27]
when clicking the reset button the gunshot appears to be sounding but not for long enough so it sounds weird. It sounds right when clicking on the cans though. Depends on if we want the gunshot sound to happen on any and every click.

**Comment by CodiushMaximush** [comment]
Currently the gunshot fires on every click. It's getting interrupted when the scene reloads. We can fix this by not playing the sound when the button is clicked, or allowing the gunshot to finish by not destroying the sound source when reloading the scene. Deciding when and when not to play the sound may be difficult as we only don't want to play the sound when clicking this one button. It may be more cinematic to have your last shot echo during some kind of transition. 

Check out: https://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

**Comment by CodiushMaximush** [comment]
Alternatively,  move the restart button to a pause menu that makes the gun not fire when it's active.
